const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const cfg=window.TANDERA_CONFIG||{}, queue=window.TanderaOffline;
const state={pallet:null,stream:null,detector:null,detecting:false,editingCode:'',syncing:false};
function ensureUI(){if(!$('#syncStatus'))$('#adminBtn')?.insertAdjacentHTML('beforebegin','<span id="syncStatus" class="syncStatus">Comprobando…</span>');if(!$('#refreshBtn'))$('#adminBtn')?.insertAdjacentHTML('beforebegin','<button id="refreshBtn" class="iconBtn">↻</button>');if(!$('#editModal'))document.body.insertAdjacentHTML('beforeend',`<div id="editModal" class="modal hidden"><div class="modalCard"><div class="row"><h2>Editar bultos</h2><button id="cancelEdit" class="iconBtn">×</button></div><label>Nombre del código<input id="editCode"></label><label>Cantidad</label><div class="quantityEditor"><button id="minusQty">−</button><input id="editQty" type="number" min="0" max="9999"><button id="plusQty">＋</button></div><p class="muted">La cantidad 0 elimina este código.</p><button id="saveEdit" class="primary big">Guardar cambios</button><button id="deleteCode" class="danger">Eliminar todos estos bultos</button></div></div>`)}ensureUI();
async function api(action,data={},silent=false){if(!cfg.API_URL||cfg.API_URL.includes('PEGAR_AQUI'))throw new Error('Configura API_URL.');if(!navigator.onLine)throw new TypeError('Sin conexión');if(!silent)loading(true);const c=new AbortController(),timer=setTimeout(()=>c.abort(),25000);try{const r=await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...data,action,apiKey:cfg.API_KEY||''}),redirect:'follow',signal:c.signal}),j=await r.json();if(!j.ok)throw new Error(j.error||'Error del servidor');return j.data}catch(e){if(e.name==='AbortError')throw new TypeError('La conexión tardó demasiado');throw e}finally{clearTimeout(timer);if(!silent)loading(false)}}
function view(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));if(id!=='scan')stopCamera();scrollTo(0,0)}function loading(on){$('#loading')?.classList.toggle('hidden',!on)}function toast(m){const x=$('#toast');if(!x)return;x.textContent=m;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),3000)}function operator(){return $('#operator').value.trim()}function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
function offlinePalletId(){const d=new Date(),date=String(d.getFullYear()).slice(2)+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0');return'T-'+date+'-X'+Math.random().toString(36).slice(2,6).toUpperCase()}function persist(){if(state.pallet){localStorage.setItem('tandera_active_data',JSON.stringify(state.pallet));localStorage.setItem('tandera_open',state.pallet.pallet.ID_TARIMA)}else{localStorage.removeItem('tandera_active_data');localStorage.removeItem('tandera_open')}}function loadPallet(){try{return JSON.parse(localStorage.getItem('tandera_active_data')||'null')}catch(e){return null}}
async function status(){const n=await queue.count(),el=$('#syncStatus');if(!el)return;el.className='syncStatus '+(!navigator.onLine?'offline':n?'pending':'');el.textContent=!navigator.onLine?`Sin conexión · ${n} pendientes`:n?`En línea · ${n} pendientes`:'En línea · Sincronizado'}
window.addEventListener('tandera-queue',()=>{status();if(navigator.onLine)syncQueue()});window.addEventListener('online',()=>{toast('Conexión recuperada. Sincronizando…');syncQueue()});
async function processOp(op){if(op.type==='create')return api('createPallet',op.payload,true);if(op.type==='scan')return api('scan',op.payload,true);if(op.type==='close'){const d=await api('assignLocation',op.payload,true);if(state.pallet?.pallet.ID_TARIMA===op.payload.idTarima){state.pallet=d;renderDetail(d)}return d}throw new Error('Operación desconocida')}
async function syncQueue(){if(state.syncing||!navigator.onLine)return;state.syncing=true;try{await queue.sync(processOp)}catch(e){toast('Sincronización pendiente: '+e.message)}finally{state.syncing=false;status()}}
async function init(){fillLocations();$('#operator').value=localStorage.getItem('tandera_operator')||'';state.pallet=loadPallet();$('#continueBtn').classList.toggle('hidden',!state.pallet);const cached=JSON.parse(localStorage.getItem('tandera_pallets')||'[]');renderPallets(cached);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});if(navigator.onLine)try{const d=await api('bootstrap',{},true);renderPallets(d.pallets);localStorage.setItem('tandera_pallets',JSON.stringify(d.pallets))}catch(e){toast('Trabajando con datos guardados.')}status();syncQueue()}
$('#newBtn').onclick=async()=>{const id=offlinePalletId(),now=new Date().toISOString();localStorage.setItem('tandera_operator',operator());state.pallet={pallet:{ID_TARIMA:id,FECHA_CREACION:now,ESTADO:'ABIERTA',TOTAL_BULTOS:0,ID_UBICACION:'',UBICACION_CORTA:'',UBICACION_COMPLETA:'',FECHA_CIERRE:'',OPERADOR:operator()},total:0,summary:[],recent:[]};persist();renderScan();view('scan');await queue.add('create',{operationId:uuid(),idTarima:id,operador:operator()});syncQueue()};
$('#continueBtn').onclick=()=>{state.pallet=loadPallet();if(!state.pallet)return toast('No hay tarima abierta.');renderScan();view('scan');syncQueue()};
$('#scanForm').onsubmit=async e=>{e.preventDefault();const i=$('#code'),code=i.value.trim().toUpperCase();if(!code||!state.pallet)return;const scanId=uuid(),id=state.pallet.pallet.ID_TARIMA;state.pallet.total++;state.pallet.pallet.TOTAL_BULTOS=state.pallet.total;const row=state.pallet.summary.find(x=>x.codigo===code);row?row.cantidad++:state.pallet.summary.push({codigo:code,cantidad:1});state.pallet.summary.sort((a,b)=>a.codigo.localeCompare(b.codigo));persist();i.value='';$('#lastScan').textContent='✓ '+code+' guardado en el teléfono · '+state.pallet.total+' bultos';renderScan();i.focus();navigator.vibrate?.(80);await queue.add('scan',{operationId:scanId,idEscaneo:scanId,idTarima:id,codigo:code,operador:operator(),fechaEscaneo:new Date().toISOString()});syncQueue()};
function renderScan(){if(!state.pallet)return;const d=state.pallet;$('#palletId').textContent=d.pallet.ID_TARIMA;$('#total').textContent=d.total;$('#summary').innerHTML=d.summary.length?d.summary.map(x=>`<div class="summaryRow"><span>${esc(x.codigo)}</span><span class="summaryTools"><b>${x.cantidad}</b><button class="editItem" data-code="${esc(x.codigo)}">✎</button></span></div>`).join(''):'<p class="muted">Aún no hay escaneos.</p>';$$('.editItem').forEach(b=>b.onclick=()=>openEditor(b.dataset.code));persist()}$('#finishBtn').onclick=()=>view('location');
function fillLocations(){$('#aisle').innerHTML='ABCDEFGHIJKLMNOPQRSTU'.split('').map(x=>`<option ${x==='S'?'selected':''}>${x}</option>`).join('');$('#position').innerHTML=Array.from({length:65},(_,i)=>i+11).map(x=>`<option ${x===36?'selected':''}>${x}</option>`).join('');$('#level').innerHTML=Array.from({length:6},(_,i)=>'N'+(i+1)).map(x=>`<option ${x==='N4'?'selected':''}>${x}</option>`).join('');updateLocation()}function updateLocation(){const s=`${$('#aisle').value}/${$('#position').value}/${$('#level').value}`;$('#shortLocation').textContent=s;$('#fullLocation').textContent='TEX 1/TANDERA/'+s}['#aisle','#position','#level'].forEach(s=>$(s).onchange=updateLocation);
$('#closeBtn').onclick=async()=>{if(!state.pallet)return;const loc=$('#shortLocation').textContent,id=state.pallet.pallet.ID_TARIMA;await queue.add('close',{operationId:uuid(),idTarima:id,idUbicacion:loc});state.pallet.pallet.ESTADO='PENDIENTE_SYNC';state.pallet.pallet.UBICACION_CORTA=loc;state.pallet.pallet.UBICACION_COMPLETA='TEX 1/TANDERA/'+loc;renderDetail(state.pallet);localStorage.removeItem('tandera_active_data');localStorage.removeItem('tandera_open');$('#continueBtn').classList.add('hidden');view('detail');toast(navigator.onLine?'Cierre en sincronización…':'Cierre guardado en el teléfono');syncQueue()};
$('#adminBtn').onclick=async()=>{if(navigator.onLine)await refreshPallets();view('admin')};$('#refreshBtn').onclick=async()=>{if(navigator.onLine)await syncQueue();location.reload()};
async function refreshPallets(){try{const rows=await api('listPallets',{query:$('#search').value});renderPallets(rows);localStorage.setItem('tandera_pallets',JSON.stringify(rows))}catch(e){renderPallets(JSON.parse(localStorage.getItem('tandera_pallets')||'[]'));toast('Mostrando datos guardados.')}}
function renderPallets(rows){$('#palletList').innerHTML=rows.length?rows.map(x=>`<article data-id="${esc(x.ID_TARIMA)}"><b>${esc(x.ID_TARIMA)}</b><div class="meta"><span>${esc(x.UBICACION_CORTA||'Sin ubicación')} · ${x.TOTAL_BULTOS||0} bultos</span><span class="pill">${esc(x.ESTADO)}</span></div></article>`).join(''):'<p class="muted">No hay tarimas disponibles.</p>';$$('#palletList article').forEach(x=>x.onclick=async()=>{if(!navigator.onLine)return toast('El detalle requiere conexión.');try{const d=await api('palletDetail',{idTarima:x.dataset.id});renderDetail(d);view('detail')}catch(e){toast(e.message)}})}
function renderDetail(d){$('#detailBody').innerHTML=`<h2>${esc(d.pallet.ID_TARIMA)}</h2><div class="card"><p><b>Estado:</b> ${esc(d.pallet.ESTADO)}</p><p><b>Total:</b> ${d.total} bultos</p><p><b>Ubicación:</b> ${esc(d.pallet.UBICACION_COMPLETA||'Sin asignar')}</p></div><div class="card"><h3>Concentrado por código</h3><div class="summary">${d.summary.map(x=>`<div><span>${esc(x.codigo)}</span><b>${x.cantidad}</b></div>`).join('')||'<p class="muted">Sin escaneos</p>'}</div></div>`}
let searchTimer;$('#search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(refreshPallets,300)};$$('[data-back]').forEach(x=>x.onclick=()=>view(x.dataset.back));
$('#exportBtn').onclick=async()=>{try{const d=await api('exportOdoo'),b=new Blob(['\ufeff'+d.csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=d.filename;a.click();URL.revokeObjectURL(a.href)}catch(e){toast('La exportación requiere conexión.')}};$('#syncBtn')?.addEventListener('click',async()=>{if(!navigator.onLine)return toast('Sin conexión.');if(!confirm('¿Reconstruir datos usando ESCANEOS?'))return;try{await syncQueue();const d=await api('syncDerived');await refreshPallets();toast(`Sincronizado: ${d.scans} escaneos`)}catch(e){toast(e.message)}});
async function openEditor(code){if(!navigator.onLine)return toast('Conéctate para editar registros confirmados.');await syncQueue();if(await queue.count())return toast('Espera la sincronización.');try{state.pallet=await api('palletDetail',{idTarima:state.pallet.pallet.ID_TARIMA});renderScan();const row=state.pallet.summary.find(x=>x.codigo===code);if(!row)throw new Error('El código ya no existe.');state.editingCode=code;$('#editCode').value=code;$('#editQty').value=row.cantidad;$('#editModal').classList.remove('hidden')}catch(e){toast(e.message)}}function closeEditor(){$('#editModal').classList.add('hidden');state.editingCode=''}$('#cancelEdit').onclick=closeEditor;$('#editModal').onclick=e=>{if(e.target===$('#editModal'))closeEditor()};$('#minusQty').onclick=()=>$('#editQty').value=Math.max(0,Number($('#editQty').value||0)-1);$('#plusQty').onclick=()=>$('#editQty').value=Math.min(9999,Number($('#editQty').value||0)+1);
async function saveEdit(q){const code=$('#editCode').value.trim().toUpperCase(),quantity=q===undefined?Number($('#editQty').value):q;if(!code)return toast('Escribe el código.');try{state.pallet=await api('adjustCode',{idTarima:state.pallet.pallet.ID_TARIMA,oldCode:state.editingCode,newCode:code,quantity,operador:operator()});closeEditor();renderScan();toast('Tarima actualizada')}catch(e){toast(e.message)}}$('#saveEdit').onclick=()=>saveEdit();$('#deleteCode').onclick=()=>{if(confirm('¿Eliminar todos estos bultos?'))saveEdit(0)};
$('#cameraBtn').onclick=()=>state.stream?stopCamera():startCamera();async function startCamera(){if(!('BarcodeDetector'in window))return toast('Usa el campo manual o lector tipo teclado.');try{state.detector=new BarcodeDetector({formats:['code_128','code_39','ean_13','ean_8','qr_code']});state.stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('#video').srcObject=state.stream;await $('#video').play();$('#cameraBox').classList.remove('hidden');$('#cameraBtn').textContent='Detener cámara';state.detecting=true;detectLoop()}catch(e){toast('No se pudo abrir la cámara.')}}async function detectLoop(){if(!state.detecting)return;try{const c=await state.detector.detect($('#video'));if(c[0]){$('#code').value=c[0].rawValue;$('#scanForm').requestSubmit();stopCamera();return}}catch(e){}requestAnimationFrame(detectLoop)}function stopCamera(){state.detecting=false;state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;$('#cameraBox').classList.add('hidden');$('#cameraBtn').textContent='📷 Activar cámara'}
init();
